/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./*.html', './js/**/*.js', './css/tailwind.input.css'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d3d5d5',
        error: '#b02500',
        'surface-container-high': '#e1e3e3',
        'on-primary-fixed': '#3a4a00',
        'error-dim': '#b92902',
        'on-surface-variant': '#5a5c5c',
        'on-secondary-fixed-variant': '#5c5b5b',
        'on-primary-fixed-variant': '#526900',
        'tertiary-fixed': '#ff81f5',
        'primary-fixed': '#cafd00',
        'surface-container-highest': '#dbdddd',
        'on-primary': '#e1ff88',
        'error-container': '#f95630',
        'on-primary-container': '#4a5e00',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#d7d4d3',
        'surface-variant': '#dbdddd',
        'surface-tint': '#4e6300',
        'on-secondary-fixed': '#403f3f',
        surface: '#f6f6f6',
        'inverse-on-surface': '#9c9d9d',
        'on-tertiary': '#ffeef8',
        'primary-fixed-dim': '#beee00',
        'on-surface': '#2d2f2f',
        primary: '#4e6300',
        'on-secondary': '#f5f2f1',
        'surface-container': '#e7e8e8',
        'primary-container': '#cafd00',
        'on-secondary-container': '#525151',
        'on-background': '#2d2f2f',
        'on-error-container': '#520c00',
        'surface-bright': '#f6f6f6',
        'on-tertiary-fixed-variant': '#6a006a',
        'inverse-surface': '#0c0f0f',
        'secondary-container': '#e5e2e1',
        'tertiary-container': '#ff81f5',
        'inverse-primary': '#cafd00',
        'on-tertiary-container': '#5b005b',
        tertiary: '#a400a4',
        'surface-container-low': '#f0f1f1',
        'secondary-dim': '#504f4f',
        'tertiary-dim': '#900090',
        'secondary-fixed': '#e5e2e1',
        'on-tertiary-fixed': '#320032',
        'primary-dim': '#435600',
        outline: '#767777',
        'outline-variant': '#acadad',
        'on-error': '#ffefec',
        background: '#f6f6f6',
        secondary: '#5c5b5b',
        'tertiary-fixed-dim': '#ff61f8',
      },
      fontFamily: {
        headline: ['Lexend', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        label: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: { DEFAULT: '0px', lg: '0px', xl: '0px', full: '9999px' },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
